//html elments
const container = document.createElement("div");
container.classList = "container";
document.body.appendChild(container);
const head = document.createElement("h1");
container.appendChild(head);
const myForm = document.createElement("form");
myForm.id = "myForm";
container.appendChild(myForm);
const firstName = document.createElement("label");
firstName.htmlFor = "firstName";
firstName.textContent = "First Name";
myForm.appendChild(firstName);
const firstName1 = document.createElement("input");
firstName1.type = "text";
firstName1.id = "firstName";
firstName.required = "true";
myForm.appendChild(firstName1);
const br = document.createElement("br");
myForm.appendChild(br);
const lastName = document.createElement("label");
lastName.htmlFor = "lastName";
lastName.textContent = "Last Name";
myForm.appendChild(lastName);
const lastName1 = document.createElement("input");
lastName1.type = "text";
lastName1.id = "lastName";
lastName1.required = "true";
myForm.appendChild(lastName1);
const br1 = document.createElement("br");
myForm.appendChild(br1);
const address = document.createElement("label");
address.htmlFor = "address";
address.textContent = "Address";
myForm.appendChild(address);
const address1 = document.createElement("input");
address1.type = "text";
address1.id = "address";
address1.required = "true"
myForm.appendChild(address1);
const br2 = document.createElement("br");
myForm.appendChild(br2);
const pincode = document.createElement("label");
pincode.htmlFor = "pincode";
pincode.textContent = "Pincode";
myForm.appendChild(pincode);
const pincode1 = document.createElement("input");
pincode1.type = "number";
pincode1.id = "pincode";
pincode1.required = "true";
myForm.appendChild(pincode1);
const br3 = document.createElement("br");
myForm.appendChild(br3);
const gender = document.createElement("label");
gender.textContent = "Gender";
myForm.appendChild(gender);
const br17 = document.createElement("br");
myForm.appendChild(br17);
const gender11 = document.createElement("label");
gender11.htmlFor = "gender";
gender11.textContent = "Male";
myForm.appendChild(gender11);
const gender1 = document.createElement("input");
gender1.type = "radio";
gender1.value = "Male";
gender1.name = "gender";
gender1.required = "true";
myForm.appendChild(gender1);
const gender22 = document.createElement("label");
gender22.htmlFor = "gender";
gender22.textContent = "Female";
myForm.appendChild(gender22);
const gender2 = document.createElement("input");
gender2.type = "radio";
gender2.value = "Female";
gender2.name = "gender";
gender2.required = "true";
myForm.appendChild(gender2);
const br4 = document.createElement("br");
myForm.appendChild(br4);
const br5 = document.createElement("br");
myForm.appendChild(br5);
const choiceofFood = document.createElement("label");
choiceofFood.textContent = "Choice of Food (select at least 2):"
myForm.appendChild(choiceofFood);
const br6 = document.createElement("br");
myForm.appendChild(br6);
const labelOffoods = document.createElement("label");
labelOffoods.textContent = "Chicken Briyani";
myForm.appendChild(labelOffoods);
const inputOffoods = document.createElement("input");
inputOffoods.type = "checkbox";
inputOffoods.name = "food";
inputOffoods.value = "Chicken Briyani";
inputOffoods.id = "foos";
labelOffoods.appendChild(inputOffoods);
const br7 = document.createElement("br");
myForm.appendChild(br7);
const labelOffoods1 = document.createElement("label");
labelOffoods1.textContent = "Mutton Briyani";
myForm.appendChild(labelOffoods1);
const inputOffoods1 = document.createElement("input");
inputOffoods1.type = "checkbox";
inputOffoods1.name = "food";
inputOffoods1.value = "Mutton Briyani";
inputOffoods1.style = "margin-left: 44px";
inputOffoods1.id = "foos";
labelOffoods1.appendChild(inputOffoods1);
const br8 = document.createElement("br");
myForm.appendChild(br8);
const labelOffoods2 = document.createElement("label");
labelOffoods2.textContent = "Chicken 65 ";
myForm.appendChild(labelOffoods2);
const inputOffoods2 = document.createElement("input");
inputOffoods2.type = "checkbox";
inputOffoods2.name = "food";
inputOffoods2.value = "Chicken 65 ";
inputOffoods2.style = "margin-left: 61px";
inputOffoods2.id = "foos";
labelOffoods2.appendChild(inputOffoods2);
const br9 = document.createElement("br");
myForm.appendChild(br9);
const labelOffoods3 = document.createElement("label");
labelOffoods3.textContent = "Chicken Gravy ";
myForm.appendChild(labelOffoods3);
const inputOffoods3 = document.createElement("input");
inputOffoods3.type = "checkbox";
inputOffoods3.name = "food";
inputOffoods3.value = "Chicken Gravy";
inputOffoods3.style = "margin-left: 36px";
inputOffoods3.id = "foos";
labelOffoods3.appendChild(inputOffoods3);
const br0 = document.createElement("br");
myForm.appendChild(br0);
const labelOffoods4 = document.createElement("label");
labelOffoods4.textContent = "Mutton Gravy ";
myForm.appendChild(labelOffoods4);
const inputOffoods4 = document.createElement("input");
inputOffoods4.type = "checkbox";
inputOffoods4.name = "food";
inputOffoods4.value = "Mutton Gravy ";
inputOffoods4.style = "margin-left: 45px";
inputOffoods4.id = "foos";
labelOffoods4.appendChild(inputOffoods4);
const br18 = document.createElement("br");
myForm.appendChild(br18);
const br11 = document.createElement("br");
myForm.appendChild(br11);
const state = document.createElement("label");
state.htmlFor = "state";
state.textContent = "State:";
myForm.appendChild(state);
const state1 = document.createElement("input");
state1.type = "text";
state1.id = "state";
state1.required = "true";
myForm.appendChild(state1);
const br12 = document.createElement("br");
myForm.appendChild(br12);
const country = document.createElement("label");
country.htmlFor = "country";
country.textContent = "Country:";
myForm.appendChild(country);
const country1 = document.createElement("input");
country1.type = "text";
country1.id = "country";
country1.required = "true";
myForm.appendChild(country1);
const br13 = document.createElement("br");
myForm.appendChild(br13);
const button = document.createElement("button");
button.type = "submit";
button.textContent = "Submit";
myForm.appendChild(button);
const reset = document.createElement("button");
reset.type = "reset";
reset.textContent = "Reset";
myForm.appendChild(reset);
const container1 = document.createElement("div");
container1.classList = "container";
document.body.appendChild(container1);
const head1 = document.createElement("h1");
container1.appendChild(head1);
const dataTable = document.createElement("table");
dataTable.id = "dataTable";
container1.appendChild(dataTable);
const thead = document.createElement("thead");
dataTable.appendChild(thead);
const tr = document.createElement("tr");
thead.appendChild(tr);
const th = document.createElement("th");
th.textContent = "First Name";
tr.appendChild(th);
const th1 = document.createElement("th");
th1.textContent = "Last Name";
tr.appendChild(th1);
const th2 = document.createElement("th");
th2.textContent = "Address";
tr.appendChild(th2);
const th3 = document.createElement("th");
th3.textContent = "Pincode";
tr.appendChild(th3);
const th4 = document.createElement("th");
th4.textContent = "Gender";
tr.appendChild(th4);
const th5 = document.createElement("th");
th5.textContent = "Food";
tr.appendChild(th5);
const th6 = document.createElement("th");
th6.textContent = "State";
tr.appendChild(th6);
const th7 = document.createElement("th");
th7.textContent = "Country";
tr.appendChild(th7);
const tbody = document.createElement("tbody");
dataTable.appendChild(tbody);
//logics
document.addEventListener("DOMContentLoaded", function () {
  const form = document.getElementById("myForm");
  const dataTable = document.getElementById("dataTable").getElementsByTagName("tbody")[0];
  const checkboxes = form.querySelectorAll('input[type="checkbox"][name="food"]');
  form.addEventListener("submit", function (event) {
    event.preventDefault();
       const selectedCheckboxes = Array.from(checkboxes).filter(checkbox => checkbox.checked);
                if (selectedCheckboxes.length < 2 || selectedCheckboxes.length > 5) {
                    alert("Select a minimum of 2 and a maximum of 5 options.");
                    return;
                }
                const selectedFoods = selectedCheckboxes.map(checkbox => checkbox.value).join(", ");
    const firstName = form.querySelector("#firstName").value;
    const lastName = form.querySelector("#lastName").value;
    const address = form.querySelector("#address").value;
    const pincode = form.querySelector("#pincode").value;
    const gender = form.querySelector('input[name="gender"]:checked').value;
    const state = form.querySelector("#state").value;
    const country = form.querySelector("#country").value;
    const newRow = dataTable.insertRow();
    const cell1 = newRow.insertCell(0);
    const cell2 = newRow.insertCell(1);
    const cell3 = newRow.insertCell(2);
    const cell4 = newRow.insertCell(3);
    const cell5 = newRow.insertCell(4);
    const cell6 = newRow.insertCell(5);
    const cell7 = newRow.insertCell(6);
    const cell8 = newRow.insertCell(7);

    cell1.innerHTML = firstName;
    cell2.innerHTML = lastName;
    cell3.innerHTML = address;
    cell4.innerHTML = pincode;
    cell5.innerHTML = gender;
    cell6.innerHTML = selectedFoods;
    cell7.innerHTML = state;
    cell8.innerHTML = country;

    form.reset();
  });
});
